CREATE TABLE blocks (
    block_id TEXT PRIMARY KEY,
    _version_ INTEGER,
    access_restricted BOOLEAN,
    aka TEXT,
    call_number TEXT,
    campaigns TEXT,
    contributor_names TEXT,
    contributors TEXT,
    created_published TEXT,
    date TEXT,
    dates TEXT,
    description TEXT,
    digital_id TEXT,
    digitized BOOLEAN,
    display_offsite BOOLEAN,
    extract_timestamp TEXT,
    extract_urls TEXT,
    format_key TEXT,
    genre TEXT,
    group_key TEXT,
    hassegments BOOLEAN,
    id TEXT,
    image_url TEXT,
    index_key INTEGER,
    item TEXT,
    language TEXT,
    languages TEXT,
    location TEXT,
    locations TEXT,
    medium TEXT,
    mime_type TEXT,
    notes TEXT,
    online_format TEXT,
    original_format TEXT,
    other_formats TEXT,
    partof TEXT,
    repository TEXT,
    resources TEXT,
    rights TEXT,
    score REAL,
    shard TEXT,
    shelf_id TEXT,
    site TEXT,
    source_collection TEXT,
    source_modified TEXT,
    subject TEXT,
    subject_headings TEXT,
    subjects TEXT,
    timestamp TEXT,
    title TEXT,
    type_key TEXT,
    url TEXT
);
CREATE TABLE artifacts (
    uid INTEGER PRIMARY KEY AUTOINCREMENT,
    block_id TEXT,
    manuscript_id TEXT,
    mimetype TEXT,
    height INTEGER,
    width INTEGER,
    levels INTEGER,
    url TEXT,
    info TEXT,
    size INTEGER,
    fulltext_service TEXT,
    word_coordinates TEXT,
    FOREIGN KEY (block_id) REFERENCES blocks(block_id)
);